CREATE TABLE PESSOAS 
(
ID INTEGER PRIMARY KEY IDENTITY,
NOME VARCHAR(50) NOT NULL,
CIDADE VARCHAR(30)
);

CREATE LOGIN USUARIO WITH PASSWORD='SENHA123@';
CREATE USER USUARIO FROM LOGIN USUARIO;
EXEC sp_addrolemember 'DB_DATAREADER', 'USUARIO';
EXEC sp_addrolemember 'DB_DATAWRITER', 'USUARIO';

